_core:
  default_config_hash: jxWXrvxs35aGvK03AgkwBSO5ckqqyQABZHb0hCoLVk0
redirect_anonymous: true
redirect_url: 'http://localhost:8080'
preview_url: 'http://localhost:8080'
preview_types:
  node:
    article: article
    landing: landing
    page: page
route_sync: DECOUPLED_PREVIEW_IFRAME_ROUTE_SYNC
draft_provider: graphql_compose_preview
