name: 'DrupalX Paragraphs'
description: 'DrupalX paragraph types.'
type: 'Site'

install:
  # Core
  - link
  - media
  - media_library
  - options
  - text
  # Contrib
  - material_icons
  - paragraphs
  - paragraphs_features
  - paragraphs_ee
  - viewfield
