#!/bin/bash

## Description: Installs DrupalX using a recipe and opens it in a browser.

ddev start
ddev composer install
ddev drush site:install minimal --verbose -y
ddev drush recipe ../recipes/drupalx-recipe
ddev drush cr

# Add consumer keys and next.js environment variables.
ddev drush scr scripts/consumers-next.php
ddev drush cr
ddev drush uli
