#!/bin/bash

## Description: Installs DrupalX and opens it in a browser.

ddev start
ddev composer install
ddev . drush si -y --verbose drupalx_graphql
ddev . drush webform-libraries-download
ddev drush uli
