name: 'DrupalX Decoupled'
description: 'Drupal installation ready to make decoupled sites using GraphQL'
type: 'Site'
recipes:
  # Core recipes with basic functionality
  # Adding tags vocabulary and taxonomy field to article
  - core/recipes/tags_taxonomy
  # Adding media image type
  - core/recipes/image_media_type
  # Adding format editors
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  # Adding user roles
  - core/recipes/administrator_role
  - core/recipes/content_editor_role
  # Adding core recommended maintenance modules
  - core/recipes/core_recommended_maintenance

install:
  # Core
  - block_content
  - ckeditor5
  - config
  - content_moderation
  - help
  - contextual
  - datetime
  - datetime_range
  - editor
  - field_ui
  - file
  - history
  - image
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - options
  - path
  - taxonomy
  - views
  - views_ui
  # Contrib
  - admin_toolbar
  - admin_toolbar_tools
  - admin_toolbar_search
  - field_group
  - gin
  - gin_login
  - gin_toolbar
  - material_icons
  - metatag
  - node_revision_delete
  - pathauto
  - paragraphs
  - paragraphs_ee
  - paragraphs_features
  - redirect
  - responsive_image
  - svg_image
  - svg_image_responsive
  - viewfield
  - webp
  # Decoupled contrib
  - decoupled_preview_iframe
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_image_style
  - graphql_compose_menus
  - graphql_compose_routes
  - graphql_compose_users
  - graphql_compose_views
  - graphql_compose_metatags
  - graphql_compose_preview
  - graphql_compose_fragments

config:
  import:
    block_content:
      # View to list custom blocks.
      - views.view.block_content
    content_moderation: '*'
    shortcut: '*'
    editor: '*'
    file: '*'
    field_ui: '*'
    menu_ui: '*'
    node:
      - views.view.content
      - views.view.content_recent
    datetime: '*'
    datetime_range: '*'
    views: '*'
    views_ui: '*'
    user:
      # View to list users.
      - views.view.user_admin_people
    #contrib
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    admin_toolbar_search: '*'
    field_group: '*'
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_toolbar: '*'
    gin_login: '*'
    material_icons: '*'
    metatag: '*'
    node_revision_delete: '*'
    pathauto: '*'
    paragraphs: '*'
    paragraphs_ee: '*'
    paragraphs_features: '*'
    redirect: '*'
    responsive_image: '*'
    svg_image: '*'
    svg_image_responsive: '*'
    viewfield: '*'
    webp: '*'
    # Decoupled contrib
    graphql_compose: '*'

  actions:
    # Set home page
    system.site:
      simple_config_update:
        page.front: /user
    # Set and unset Gin blocks.
    block.block.gin_admin:
      simple_config_update:
        status: false
    block.block.gin_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simple_config_update:
        status: false
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true
    block.block.gin_tools:
      simple_config_update:
        status: false
    # Update the admin theme to Gin in Theme settings.
    node.settings:
      simple_config_update:
        use_admin_theme: true
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'gin'
    # Set metatag defaults.
    metatag.metatag_defaults.global:
      simple_config_update:
        tags.canonical_url: '[current-page:url]'
        tags.title: '[current-page:title] | [site:name]'
    metatag.metatag_defaults.node:
      simple_config_update:
        tags.abstract: '[node:summary]'
        tags.canonical_url: '[node:url]'
        tags.description: '[node:summary]'
        tags.image_src: '[node:field_image:entity:field_media_image:entity:url]'
        tags.og_description: '[node:summary]'
        tags.og_image: '[node:field_image:entity:field_media_image:entity:url]'
        tags.og_image_url: '[node:field_image:entity:field_media_image:entity:url]'
        tags.og_site_name: '[site:name]'
        tags.og_title: '[node:title] | [site:name]'
        tags.og_type: website
        tags.og_url: '[node:url]'
        tags.title: '[node:title] | [site:name]'
     # Set permissions for content editor role.
    user.role.content_editor:
      ensure_exists:
        id: content_editor
      grantPermissions:
        - 'use text format basic_html'
        - 'use text format full_html'
