_meta:
  version: '1.0'
  entity_type: file
  uuid: envi-cle-file-4f0f-9c6e-164a416d574c
  bundle: file
  default_langcode: en
default:
  uid:
    - target_id: 1
  filename:
    - value: environmental-cleanup.jpg
  uri:
    - value: 'public://environmental-cleanup.jpg'
  filemime:
    - value: image/jpeg
  filesize:
    - value: 363553
  status:
    - value: true
  created:
    - value: 1724541785
