name: CI Tests

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  COMPOSER_MEMORY_LIMIT: -1
  SIMPLETEST_DB: sqlite://tmp/site.sqlite
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"

jobs:
  php-cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ["8.3"]
        drupal-release: ["stable"]
        composer-channel: ["stable"]

    steps:
      # Step 1: Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Setup PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, pdo_sqlite

      # Step 3: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 4: Update Composer and validate configuration
      - name: Update Composer
        run: composer --verbose self-update --${{ matrix.composer-channel }}

      - name: Validate composer.json
        run: composer --verbose validate

      # Step 5: Install dependencies
      - name: Install Composer dependencies
        run: composer --verbose install

      - name: Install NPM dependencies
        run: npm install
        working-directory: ./tests/cypress

      # Step 6: Setup and start the server
      - name: Install site
        run: ./vendor/bin/drush site-install minimal --verbose --yes --db-url=sqlite://tmp/site.sqlite --account-name=admin --account-pass=admin

      - name: Apply DrupalX Recipe
        run:  php core/scripts/drupal -v recipe ../recipes/drupalx-recipe

      - name: Start server
        run: |
          ./vendor/bin/drush runserver "$SIMPLETEST_BASE_URL" &
          until curl -s "$SIMPLETEST_BASE_URL"; do true; done > /dev/null

      # Step 7: Install Xvfb for Cypress
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1280x1024x24 &
        env:
          DISPLAY: :99.0

      # Step 8: Copy Cypress configuration and run tests
      - name: Copy Cypress configuration
        run: cp tests/cypress/cypress.config.js.shippable tests/cypress/cypress.config.js

      - name: Run Cypress tests
        run: npm run cypress
        working-directory: ./tests/cypress
        env:
          DISPLAY: :99.0

  pa11y-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Step 1: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 2: Install pa11y-ci
      - name: Install pa11y-ci
        run: npm install -g pa11y-ci

      # Step 3: Install Next.js dependencies
      - name: Install Next.js dependencies
        run: npm install
        working-directory: ./nextjs

      # Step 4: Start Storybook
      - name: Start Storybook
        run: npm run storybook &
        working-directory: ./nextjs
        env:
          DISPLAY: :99.0

      # Step 5: Wait for Storybook to be ready
      - name: Wait for Storybook to be ready
        run: npx wait-on --timeout http://localhost:6006

      # Step 6: Run Pa11y accessibility tests
      - name: Run pa11y accessibility tests
        run: |
          pa11y-ci --config .pa11yci
        working-directory: ./nextjs
        env:
          DISPLAY: :99.0
