name: Composer Security Update Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    types: [opened, synchronize, reopened]

env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  check_security_updates:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ["8.3"]
        drupal-release: ["stable"]
        composer-channel: ["stable"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: gd, pdo_sqlite

    - name: Update Composer
      run: composer --verbose self-update --${{ matrix.composer-channel }}

    - name: Validate composer.json
      run: composer --verbose validate

    - name: Install Composer dependencies
      run: composer --verbose install

    - name: Check for security updates
      id: security_check
      run: |
        set +e
        UPDATE_OUTPUT=$(composer audit --format=plain)
        AUDIT_EXIT_CODE=$?
        set -e
        echo "UPDATE_OUTPUT<<EOF" >> $GITHUB_OUTPUT
        echo "$UPDATE_OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        if [ $AUDIT_EXIT_CODE -ne 0 ]; then
          echo "UPDATES_AVAILABLE=true" >> $GITHUB_OUTPUT
        else
          echo "UPDATES_AVAILABLE=false" >> $GITHUB_OUTPUT
        fi

    - name: Update Drupal Core
      if: steps.security_check.outputs.UPDATES_AVAILABLE == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        CURRENT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        SECURITY_BRANCH="security-updates-drupal-core-${CURRENT_BRANCH}"
        git checkout -b "$SECURITY_BRANCH"
        composer update drupal/core --with-all-dependencies
        git add composer.lock
        git commit -m "Update Drupal core for security vulnerabilities" || echo "No changes to commit"

    - name: Create Pull Request
      if: steps.security_check.outputs.UPDATES_AVAILABLE == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Drupal core for security vulnerabilities
        title: 'Security: Update Drupal core dependencies'
        body: |
          This PR addresses security vulnerabilities in Drupal core dependencies.

          Security audit output:
          ```
          ${{ steps.security_check.outputs.UPDATE_OUTPUT }}
          ```

          The `composer update drupal/core --with-all-dependencies` command has been run to update Drupal core to the latest secure version.

          Please review and test these changes before merging.
        branch: security-updates-drupal-core-${{ github.sha }}
        base: ${{ github.event.pull_request.head.ref || github.base_ref }}
        delete-branch: true

    - name: Check PR creation
      if: steps.security_check.outputs.UPDATES_AVAILABLE == 'true'
      run: |
        echo "A pull request for Drupal core security updates has been created."
        echo "Please review and merge it after testing."

    - name: No updates required
      if: steps.security_check.outputs.UPDATES_AVAILABLE != 'true'
      run: |
        echo "No security updates are required at this time."
