name: PR Review and Cypress Test Creation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  review_and_create_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch the pull request ref and base branch
      run: |
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge:pr-merge
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

    - name: Ensure we're on the PR merge commit
      run: git checkout pr-merge

    - name: Get PR Diff
      run: git diff ${{ github.base_ref }} pr-merge > diff.txt

    - name: Send Diff to OpenAI
      id: openai_review
      run: |
        DIFF_CONTENT=$(cat diff.txt)
        PROMPT="As a Drupal 10 senior developer, you are tasked with reviewing a pull request and creating a Cypress test to validate the new functionality or changes introduced. The following diff highlights the lines that have been added or removed, along with their context:

        ${DIFF_CONTENT}

        Please write a comprehensive Cypress test that covers the modified functionality. Ensure the test code is placed within the code block markers.

        ```javascript
        // Cypress test code goes here
        ```

        To facilitate the testing process, you will need to simulate a login to Drupal within the Cypress test. To do this, navigate to /user/login and use the following credentials:

        cy.get('[data-drupal-selector="edit-name"]').type('admin')
        cy.get('[data-drupal-selector="edit-pass"]').type('admin')
        cy.get('[data-drupal-selector="edit-submit"]').click()"

        ESCAPED_PROMPT=$(echo "$PROMPT" | jq -Rs .)

        RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -d "{
            \"model\": \"gpt-3.5-turbo\",
            \"messages\": [{
              \"role\": \"user\",
              \"content\": $ESCAPED_PROMPT
            }],
            \"max_tokens\": 1000
          }")
        echo "$RESPONSE" > response.txt

    - name: Parse OpenAI Response
      id: parse_response
      run: |
        CYPRESS_TEST=$(cat response.txt | jq -r '.choices[0].message.content' | sed -n '/```javascript/,/```/p' | sed '1,2d; $d')
        echo "cypress_test<<EOF" >> $GITHUB_OUTPUT
        echo "$CYPRESS_TEST" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Cypress Test File
      run: |
        echo "${{ steps.parse_response.outputs.cypress_test }}" > tests/cypress/cypress/e2e/generated-test-${{ github.event.pull_request.number }}.cy.js

    - name: Checkout original branch
      run: git checkout ${{ github.base_ref }}

    - name: Cleanup temporary files
      run: |
        rm diff.txt response.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add Cypress test for recent changes
        title: 'Add Cypress test for PR #${{ github.event.pull_request.number }}'
        body: |
          This PR adds a Cypress test to validate the changes introduced in PR #${{ github.event.pull_request.number }}.

          Please review and adjust the test as needed.
        branch: add-cypress-test-for-pr-${{ github.event.pull_request.number }}
        base: ${{ github.event.pull_request.head.ref }}

    - name: Comment on Original PR
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          A new PR has been created with a Cypress test for the changes in this PR. Please review and merge it after this PR is approved.

          [Link to test PR]({{ steps.create_pr.outputs.pull-request-url }})
