name: PR Review and Cypress Test Creation

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  review_and_create_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch the pull request ref and base branch
      run: |
        git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge:pr-merge
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

    - name: Ensure we're on the PR merge commit
      run: git checkout pr-merge

    - name: Get PR Diff
      run: git diff ${{ github.base_ref }} pr-merge > diff.txt

    - name: Send Diff to Fireworks
      id: fireworks_review
      run: |
        DIFF_CONTENT=$(cat diff.txt)
        PROMPT=$(cat << EOF
        You are a Drupal 10 senior developer reviewing a pull request.
        The following diff shows lines that have been added or removed as well as context:

        ${DIFF_CONTENT}

        Based on these changes, create a Cypress test that validates the new functionality or changes introduced.
        Ensure the test logs into Drupal at /user/login with:
          cy.get('[data-drupal-selector="edit-name"]').type('admin')
          cy.get('[data-drupal-selector="edit-pass"]').type('admin')
          cy.get('[data-drupal-selector="edit-submit"]').click()
        Provide the full Cypress test code in between the code block markers.

        \`\`\`javascript
        // Cypress test code goes here
        \`\`\`
        EOF
        )

        ESCAPED_PROMPT=$(echo "$PROMPT" | jq -Rs .)

        RESPONSE=$(curl --request POST \
          --url https://api.fireworks.ai/inference/v1/chat/completions \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer ${{ secrets.FIREWORKS_API_KEY }}" \
          --data "{
            \"model\": \"accounts/fireworks/models/firefunction-v2\",
            \"max_tokens\": 4000,
            \"top_p\": 1,
            \"top_k\": 40,
            \"presence_penalty\": 0,
            \"frequency_penalty\": 0,
            \"temperature\": 0.6,
            \"messages\": [{
              \"role\": \"user\",
              \"content\": $ESCAPED_PROMPT
            }]
          }")
        echo "$RESPONSE" > response.txt

    - name: Parse Fireworks Response
      id: parse_response
      run: |
        CYPRESS_TEST=$(cat response.txt | jq -r '.choices[0].message.content' | sed -n '/```javascript/,/```/p' | sed '1d;$d')
        echo "cypress_test<<EOF" >> $GITHUB_OUTPUT
        echo "$CYPRESS_TEST" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Cypress Test File
      run: |
        echo "${{ steps.parse_response.outputs.cypress_test }}" > tests/cypress/cypress/e2e/generated-test-${{ github.event.pull_request.number }}.cy.js

    - name: Checkout original branch
      run: git checkout ${{ github.base_ref }}

    - name: Cleanup temporary files
      run: |
        rm diff.txt response.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add Cypress test for recent changes
        title: 'Add Cypress test for PR #${{ github.event.pull_request.number }}'
        body: |
          This PR adds a Cypress test to validate the changes introduced in PR #${{ github.event.pull_request.number }}.

          Please review and adjust the test as needed.
        branch: add-cypress-test-for-pr-${{ github.event.pull_request.number }}
        base: ${{ github.event.pull_request.head.ref }}

    - name: Comment on Original PR
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          A new PR has been created with a Cypress test for the changes in this PR. Please review and merge it after this PR is approved.

          [Link to test PR](${{ steps.create_pr.outputs.pull-request-url }})
